# Generated by Django 2.2.6 on 2019-10-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.FloatField()),
                ('users_rated', models.PositiveIntegerField()),
                ('Popularity', models.PositiveSmallIntegerField()),
                ('Favorites', models.PositiveIntegerField()),
                ('Members', models.PositiveIntegerField()),
                ('animeType', models.CharField(max_length=20)),
                ('Episodes', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('premiered', models.CharField(max_length=30)),
                ('studio', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
                ('genres', models.TextField()),
            ],
        ),
    ]
