# Generated by Django 2.2.6 on 2019-10-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='animeType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='premiered',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.CharField(max_length=100),
        ),
    ]
