# Generated by Django 2.2.6 on 2019-10-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20191028_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='Episodes',
            field=models.CharField(max_length=100),
        ),
    ]
