# Generated by Django 2.2.6 on 2019-10-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20191028_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='Episodes',
            field=models.TextField(),
        ),
    ]
